### PR TITLE
innoextract update

### LINKED ISSUE #3874: Update Innoextract to compile with boost 1.85
**Describe the bug**
/run/media/disk_2/vcmi/vcmi/launcher/lib/innoextract/src/stream/slice.cpp:162: error: ‘directory_iterator’ is not a member of ‘boost::filesystem’; did you mean ‘directory_entry’?
/run/media/disk_2/vcmi/vcmi/launcher/lib/innoextract/src/stream/slice.cpp: In member function ‘bool stream::slice_reader::open_file_case_insensitive(const path_type&, const path_type&)’:
/run/media/disk_2/vcmi/vcmi/launcher/lib/innoextract/src/stream/slice.cpp:162:28: error: ‘directory_iterator’ is not a member of ‘boost::filesystem’; did you mean ‘directory_entry’?
  162 |         boost::filesystem::directory_iterator end;
      |                            ^~~~~~~~~~~~~~~~~~
      |                            directory_entry

**Additional context**
Fixed in (https://github.com/dscharrer/innoextract/commit/264c2fe6b84f90f6290c670e5f676660ec7b2387)

### PR DESCRIPTION
**Pull request by Laserlicht**
fixes #3874

### CODE REVIEW

**Comment by Laserlicht** [comment]
CI is not compatible with new innoextract. See: https://github.com/dscharrer/innoextract/pull/169
