### ISSUE TITLE
Update Innoextract to compile with boost 1.85

### ISSUE THREAD

**Issue by wb180** [vcmi/vcmi#3874]
**Describe the bug**
/run/media/disk_2/vcmi/vcmi/launcher/lib/innoextract/src/stream/slice.cpp:162: error: ‘directory_iterator’ is not a member of ‘boost::filesystem’; did you mean ‘directory_entry’?
/run/media/disk_2/vcmi/vcmi/launcher/lib/innoextract/src/stream/slice.cpp: In member function ‘bool stream::slice_reader::open_file_case_insensitive(const path_type&, const path_type&)’:
/run/media/disk_2/vcmi/vcmi/launcher/lib/innoextract/src/stream/slice.cpp:162:28: error: ‘directory_iterator’ is not a member of ‘boost::filesystem’; did you mean ‘directory_entry’?
  162 |         boost::filesystem::directory_iterator end;
      |                            ^~~~~~~~~~~~~~~~~~
      |                            directory_entry

**Additional context**
Fixed in (https://github.com/dscharrer/innoextract/commit/264c2fe6b84f90f6290c670e5f676660ec7b2387)

**Comment by Alexander-Wilms** [comment]
This doesn't seem to be fixed:

```
FAILED: CMakeFiles/innoextract.dir/src/stream/slice.cpp.o 
/usr/bin/c++ -DBOOST_ATOMIC_DYN_LINK -DBOOST_ATOMIC_NO_LIB -DBOOST_DATE_TIME_DYN_LINK -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_FILESYSTEM_NO_LIB -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_IOSTREAMS_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_SYSTEM_DYN_LINK -DBOOST_SYSTEM_NO_LIB -D_GNU_SOURCE=1 -I/run/build/innoextract/src -I/run/build/innoextract -O2 -pipe -g -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -flto -fmerge-all-constants -Wall -Wextra -Warray-bounds=2  -Wcast-qual -Wcatch-value=3 -Wconversion  -Wdouble-promotion -Wduplicated-cond -Wextra-semi -Wformat=2  -Winit-self   -Wlogical-op -Wmissing-declarations -Wnoexcept -Woverflow -Woverloaded-virtual -Wpessimizing-move -Wpointer-arith -Wredundant-decls  -Wshift-overflow -Wsign-conversion -Wstrict-null-sentinel -Wstringop-overflow=4 -Wundef -Wunused-const-variable=1 -Wunused-macros -Wvla -Wold-style-cast -Wshadow -Wno-maybe-uninitialized -ffast-math -std=c++17 -pedantic -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG -std=c++17 -MD -MT CMakeFiles/innoextract.dir/src/stream/slice.cpp.o -MF CMakeFiles/innoextract.dir/src/stream/slice.cpp.o.d -o CMakeFiles/innoextract.dir/src/stream/slice.cpp.o -c /run/build/innoextract/src/stream/slice.cpp
/run/build/innoextract/src/stream/slice.cpp: In member function ‘bool stream::slice_reader::open_file_case_insensitive(const path_type&, const path_type&)’:
/run/build/innoextract/src/stream/slice.cpp:162:28: error: ‘directory_iterator’ is not a member of ‘boost::filesystem’; did you mean ‘directory_entry’?
  162 |         boost::filesystem::directory_iterator end;
      |                            ^~~~~~~~~~~~~~~~~~
      |                            directory_entry
/run/build/innoextract/src/stream/slice.cpp:163:32: error: ‘directory_iterator’ is not a member of ‘boost::filesystem’; did you mean ‘directory_entry’?
  163 |         for(boost::filesystem::directory_iterator i(dirname); i != end; ++i) {
      |                                ^~~~~~~~~~~~~~~~~~
      |                                directory_entry
/run/build/innoextract/src/stream/slice.cpp:163:63: error: ‘i’ was not declared in this scope; did you mean ‘is’?
  163 |         for(boost::filesystem::directory_iterator i(dirname); i != end; ++i) {
      |                                                               ^
      |                                                               is
/run/build/innoextract/src/stream/slice.cpp:163:68: error: ‘end’ was not declared in this scope
  163 |         for(boost::filesystem::directory_iterator i(dirname); i != end; ++i) {
      |                                                                    ^~~
/run/build/innoextract/src/stream/slice.cpp:163:68: note: suggested alternatives:
In file included from /usr/include/c++/13.2.0/string:53,
                 from /usr/include/c++/13.2.0/bits/locale_classes.h:40,
                 from /usr/include/c++/13.2.0/bits/ios_base.h:41,
                 from /usr/include/c++/13.2.0/ios:44,
                 from /run/build/innoextract/src/stream/slice.hpp:29,
                 from /run/build/innoextract/src/stream/slice.cpp:21:
/usr/include/c++/13.2.0/bits/range_access.h:116:37: note:   ‘std::end’
  116 |   template<typename _Tp> const _Tp* end(const valarray<_Tp>&) noexcept;
      |                                     ^~~
In file included from /app/include/boost/algorithm/string/predicate.hpp:17,
                 from /run/build/innoextract/src/stream/slice.cpp:28:
/app/include/boost/range/end.hpp:104:61: note:   ‘boost::range_adl_barrier::end’
  104 | inline BOOST_DEDUCED_TYPENAME range_iterator<const T>::type end( const T& r )
      |                                                             ^~~
```

See the logs linked here:
https://github.com/flathub/eu.vcmi.VCMI/pull/159
https://github.com/flathub/eu.vcmi.VCMI/pull/158

**Comment by IvanSavenko** [comment]
@Alexander-Wilms I think you need to update innoextract as well.

What happens is that there are now 2 innoextracts in vcmi flatpak:
1. Upstream release with command line tool: https://github.com/dscharrer/innoextract
2. Our fork of innoextract, converted into library. It is submodule inside vcmi git. (not sure how flatpak handles submodules): https://github.com/vcmi/innoextract

Judging from your log, it looks like this error comes from upstream innoextract. Don't know if they have released new version with boost fix. So you probably need to either upgrade used innoextract or keep using previous version of boost.

Alternatively you can remove upstream innoextract from vcmi flatpak as well as any references to our 'vcmibuilder' tool which is now pretty much replaced by Launcher.
