### ISSUE TITLE
Failed to compile with Boost 1.86

### ISSUE THREAD

**Issue by Crandel** [vcmi/vcmi#4561]
**Describe the bug**
After updating boost to version 1.86 vcmi stop compiling

**Compile logs**

```
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/CVideoHandler.cpp:442:3: warning: 'avcodec_close' is deprecated [-Wdeprecated-declarations]
  442 |                 avcodec_close(codecContext);
      |                 ^
/usr/include/libavcodec/avcodec.h:2386:1: note: 'avcodec_close' has been explicitly marked deprecated here
 2386 | attribute_deprecated
      | ^
/usr/include/libavutil/attributes.h:100:49: note: expanded from macro 'attribute_deprecated'
  100 | #    define attribute_deprecated __attribute__((deprecated))
      |                                                 ^
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/CVideoHandler.cpp:600:3: warning: 'avcodec_close' is deprecated [-Wdeprecated-declarations]
  600 |                 avcodec_close(codecContextAudio);
      |                 ^
/usr/include/libavcodec/avcodec.h:2386:1: note: 'avcodec_close' has been explicitly marked deprecated here
 2386 | attribute_deprecated
      | ^
/usr/include/libavutil/attributes.h:100:49: note: expanded from macro 'attribute_deprecated'
  100 | #    define attribute_deprecated __attribute__((deprecated))
      |                                                 ^
[100%] Building CXX object client/CMakeFiles/vcmiclient.dir/NetPacksClient.cpp.o
[100%] Building CXX object client/CMakeFiles/vcmiclient.dir/NetPacksLobbyClient.cpp.o
[100%] Building CXX object client/CMakeFiles/vcmiclient.dir/ServerRunner.cpp.o
2 warnings generated.
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/ServerRunner.cpp:63:7: error: member access into incomplete type 'boost::process::child'
   63 |         child->terminate();
      |              ^
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/ServerRunner.h:49:7: note: forward declaration of 'boost::process::child'
   49 | class child;
      |       ^
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/ServerRunner.cpp:68:7: error: member access into incomplete type 'boost::process::child'
   68 |         child->wait();
      |              ^
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/ServerRunner.h:49:7: note: forward declaration of 'boost::process::child'
   49 | class child;
      |       ^
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/ServerRunner.cpp:73:14: error: member access into incomplete type 'boost::process::child'
   73 |         return child->exit_code();
      |                     ^
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/ServerRunner.h:49:7: note: forward declaration of 'boost::process::child'
   49 | class child;
      |       ^
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/ServerRunner.cpp:87:43: error: reference to 'child' is ambiguous
   87 |         child = std::make_unique<boost::process::child>(serverPath, args, ec, boost::process::std_out > logPath);
      |                                                  ^
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/ServerRunner.h:49:7: note: candidate found by name lookup is 'boost::process::child'
   49 | class child;
      |       ^
/usr/include/boost/process/v1/detail/execute_impl.hpp:45:7: note: candidate found by name lookup is 'boost::process::v1::child'
   45 | class child;
      |       ^
In file included from <built-in>:1:
In file included from /data/linux/bb/vcmi/src/vcmi-1.5.7/build/client/CMakeFiles/vcmiclient.dir/cmake_pch.hxx:5:
In file included from /data/linux/bb/vcmi/src/vcmi-1.5.7/client/StdInc.h:12:
In file included from /data/linux/bb/vcmi/src/vcmi-1.5.7/client/../Global.h:123:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/memory:78:
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/bits/unique_ptr.h:91:16: error: invalid application of 'sizeof' to an incomplete type 'boost::process::child'
   91 |         static_assert(sizeof(_Tp)>0,
      |                       ^~~~~~~~~~~
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/bits/unique_ptr.h:398:4: note: in instantiation of member function 'std::default_delete<boost::process::child>::operator()' requested here
  398 |           get_deleter()(std::move(__ptr));
      |           ^
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/ServerRunner.cpp:58:22: note: in instantiation of member function 'std::unique_ptr<boost::process::child>::~unique_ptr' requested here
   58 | ServerProcessRunner::ServerProcessRunner() = default;
      |                      ^
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/ServerRunner.h:49:7: note: forward declaration of 'boost::process::child'
   49 | class child;
      |       ^
In file included from <built-in>:1:
In file included from /data/linux/bb/vcmi/src/vcmi-1.5.7/build/client/CMakeFiles/vcmiclient.dir/cmake_pch.hxx:5:
In file included from /data/linux/bb/vcmi/src/vcmi-1.5.7/client/StdInc.h:12:
In file included from /data/linux/bb/vcmi/src/vcmi-1.5.7/client/../Global.h:123:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/memory:78:
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/bits/unique_ptr.h:1076:34: error: allocation of incomplete type 'boost::process::child'
 1076 |     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
      |                                  ^~~
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/ServerRunner.cpp:87:15: note: in instantiation of function template specialization 'std::make_unique<boost::process::child, boost::filesystem::path &, std::vector<std::basic_string<char>> &, std::error_code &, boost::process::detail::posix::file_out<1, -1>>' requested here
   87 |         child = std::make_unique<boost::process::child>(serverPath, args, ec, boost::process::std_out > logPath);
      |                      ^
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/ServerRunner.h:49:7: note: forward declaration of 'boost::process::child'
   49 | class child;
      |       ^
6 errors generated.
make[2]: *** [client/CMakeFiles/vcmiclient.dir/build.make:2701: client/CMakeFiles/vcmiclient.dir/ServerRunner.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1096: client/CMakeFiles/vcmiclient.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: vcmi-exit status 4

```

**To Reproduce**
1. Build vcmi with boost 1.86

**Expected behavior**
Successful build

**Actual behavior**
Build failed

**Did it work earlier?**
It was working fine on boost 1.85

**Screenshots**

**Version**
 - OS: Arch Linux
 - Version: 1.5.7

**Comment by IvanSavenko** [comment]
avcodec stuff should be already fixed in develop build / 1.6, for 1.5 you can disable strict compilation or simply remove those lines - they are no longer necessary in newer ffmpeg

boost stuff - not sure, there were apparently a lot of changes in boost::process. They might have some compatibility define that we can use for now

**Comment by IvanSavenko** [comment]
Try changing 
```cpp
namespace boost::process {
class child;
}
```
to 
```
namespace boost::process::v1 {
class child;
}
```
in client/ServerRunner.h, line 50

**Comment by IvanSavenko** [comment]
Oh, and also
```std::unique_ptr<boost::process::child> child;```
to
```std::unique_ptr<boost::process::v1::child> child;```
a bit lower

**Comment by Crandel** [comment]
Unfortunately it was not helping. I've replaced in both ServerRunner.h/cpp boost::process::child to boost::process::v1::child everywhere, but still get compilation errors

```
In file included from /usr/include/boost/smart_ptr/detail/requires_cxx11.hpp:9,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:17,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /usr/include/boost/exception/detail/shared_ptr.hpp:13,
                 from /usr/include/boost/exception/info.hpp:13,
                 from /usr/include/boost/algorithm/hex.hpp:30,
                 from /data/linux/bb/vcmi/src/vcmi-1.5.7/Global.h:158,
                 from /data/linux/bb/vcmi/src/vcmi-1.5.7/client/StdInc.h:12,
                 from /data/linux/bb/vcmi/src/vcmi-1.5.7/build/client/CMakeFiles/vcmiclient.dir/cmake_pch.hxx:5,
                 from <command-line>:
/usr/include/boost/process/io.hpp:8:1: note: ‘#pragma message: This header is deprecated. Use <boost/process/v1/io.hpp> instead.’
    8 | BOOST_HEADER_DEPRECATED("<boost/process/v1/io.hpp>")
      | ^~~~~~~~~~~~~~~~~~~~~~~
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/ServerRunner.cpp: In member function ‘virtual void ServerProcessRunner::shutdown()’:
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/ServerRunner.cpp:63:14: error: invalid use of incomplete type ‘class boost::process::child’
   63 |         child->terminate();
      |              ^~
In file included from /data/linux/bb/vcmi/src/vcmi-1.5.7/client/ServerRunner.cpp:12:
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/ServerRunner.h:49:7: note: forward declaration of ‘class boost::process::child’
   49 | class child;
      |       ^~~~~
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/ServerRunner.cpp: In member function ‘virtual void ServerProcessRunner::wait()’:
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/ServerRunner.cpp:68:14: error: invalid use of incomplete type ‘class boost::process::child’
   68 |         child->wait();
      |              ^~
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/ServerRunner.h:49:7: note: forward declaration of ‘class boost::process::child’
   49 | class child;
      |       ^~~~~
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/ServerRunner.cpp: In member function ‘virtual int ServerProcessRunner::exitCode()’:
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/ServerRunner.cpp:73:21: error: invalid use of incomplete type ‘class boost::process::child’
   73 |         return child->exit_code();
      |                     ^~
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/ServerRunner.h:49:7: note: forward declaration of ‘class boost::process::child’
   49 | class child;
      |       ^~~~~
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/ServerRunner.cpp: In member function ‘virtual void ServerProcessRunner::start(uint16_t, bool, std::shared_ptr<StartInfo>)’:
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/ServerRunner.cpp:87:116: error: no match for ‘operator=’ (operand types are ‘std::unique_ptr<boost::process::child>’ and ‘std::__detail::__unique_ptr_t<boost::process::v1::child>’)
   87 |         child = std::make_unique<boost::process::v1::child>(serverPath, args, ec, boost::process::std_out > logPath);
      |                                                                                                                    ^
In file included from /usr/include/c++/14.2.1/memory:78,
                 from /data/linux/bb/vcmi/src/vcmi-1.5.7/Global.h:123:
/usr/include/c++/14.2.1/bits/unique_ptr.h:424:9: note: candidate: ‘template<class _Up, class _Ep> typename std::enable_if<std::__and_<std::__and_<std::is_convertible<typename std::unique_ptr<_Up, _Ep>::pointer, typename std::__uniq_ptr_impl<_Tp, _Dp>::pointer>, std::__not_<std::is_array<_Up> > >, std::is_assignable<_T2&, _U2&&> >::value, std::unique_ptr<_Tp, _Dp>&>::type std::unique_ptr<_Tp, _Dp>::operator=(std::unique_ptr<_Up, _Ep>&&) [with _Ep = _Up; _Tp = boost::process::child; _Dp = std::default_delete<boost::process::child>]’
  424 |         operator=(unique_ptr<_Up, _Ep>&& __u) noexcept
      |         ^~~~~~~~
/usr/include/c++/14.2.1/bits/unique_ptr.h:424:9: note:   template argument deduction/substitution failed:
/usr/include/c++/14.2.1/bits/unique_ptr.h: In substitution of ‘template<class _Up, class _Ep> typename std::enable_if<std::__and_<std::__and_<std::is_convertible<typename std::unique_ptr<_Tp, _Dp>::pointer, boost::process::child*>, std::__not_<std::is_array<_Tp> > >, std::is_assignable<std::default_delete<boost::process::child>&, _U2&&> >::value, std::unique_ptr<boost::process::child>&>::type std::unique_ptr<boost::process::child>::operator=(std::unique_ptr<_Tp, _Dp>&&) [with _Up = boost::process::v1::child; _Ep = std::default_delete<boost::process::v1::child>]’:
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/ServerRunner.cpp:87:109:   required from here
   87 |         child = std::make_unique<boost::process::v1::child>(serverPath, args, ec, boost::process::std_out > logPath);
      |                                                                                                                    ^
/usr/include/c++/14.2.1/bits/unique_ptr.h:424:9: error: no type named ‘type’ in ‘struct std::enable_if<false, std::unique_ptr<boost::process::child>&>’
  424 |         operator=(unique_ptr<_Up, _Ep>&& __u) noexcept
      |         ^~~~~~~~
/usr/include/c++/14.2.1/bits/unique_ptr.h:408:19: note: candidate: ‘std::unique_ptr<_Tp, _Dp>& std::unique_ptr<_Tp, _Dp>::operator=(std::unique_ptr<_Tp, _Dp>&&) [with _Tp = boost::process::child; _Dp = std::default_delete<boost::process::child>]’
  408 |       unique_ptr& operator=(unique_ptr&&) = default;
      |                   ^~~~~~~~
/usr/include/c++/14.2.1/bits/unique_ptr.h:408:29: note:   no known conversion for argument 1 from ‘std::__detail::__unique_ptr_t<boost::process::v1::child>’ to ‘std::unique_ptr<boost::process::child>&&’
  408 |       unique_ptr& operator=(unique_ptr&&) = default;
      |                             ^~~~~~~~~~~~
/usr/include/c++/14.2.1/bits/unique_ptr.h:434:7: note: candidate: ‘std::unique_ptr<_Tp, _Dp>& std::unique_ptr<_Tp, _Dp>::operator=(std::nullptr_t) [with _Tp = boost::process::child; _Dp = std::default_delete<boost::process::child>; std::nullptr_t = std::nullptr_t]’
  434 |       operator=(nullptr_t) noexcept
      |       ^~~~~~~~
/usr/include/c++/14.2.1/bits/unique_ptr.h:434:17: note:   no known conversion for argument 1 from ‘std::__detail::__unique_ptr_t<boost::process::v1::child>’ to ‘std::nullptr_t’
  434 |       operator=(nullptr_t) noexcept
      |                 ^~~~~~~~~
/usr/include/c++/14.2.1/bits/unique_ptr.h: In instantiation of ‘void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = boost::process::child]’:
/usr/include/c++/14.2.1/bits/unique_ptr.h:398:17:   required from ‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = boost::process::child; _Dp = std::default_delete<boost::process::child>]’
  398 |           get_deleter()(std::move(__ptr));
      |           ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
/data/linux/bb/vcmi/src/vcmi-1.5.7/client/ServerRunner.cpp:58:1:   required from here
   58 | ServerProcessRunner::ServerProcessRunner() = default;
      | ^~~~~~~~~~~~~~~~~~~
/usr/include/c++/14.2.1/bits/unique_ptr.h:91:23: error: invalid application of ‘sizeof’ to incomplete type ‘boost::process::child’
   91 |         static_assert(sizeof(_Tp)>0,
      |                       ^~~~~~~~~~~
make[2]: *** [client/CMakeFiles/vcmiclient.dir/build.make:2701: client/CMakeFiles/vcmiclient.dir/ServerRunner.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:951: client/CMakeFiles/vcmiclient.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: vcmi-exit status 4
```

**Comment by fenuks** [comment]
I got it compiling with a patch below. I don't know why `client/ServerRunner.h` declares own `boost::process::child` instead of including `boost/process/child` directly, I done just that and it works.

```diff
diff --git i/client/ServerRunner.cpp w/client/ServerRunner.cpp
index 2a7a0791e..927673fac 100644
--- i/client/ServerRunner.cpp
+++ w/client/ServerRunner.cpp
@@ -15,11 +15,6 @@
 #include "../lib/CThreadHelper.h"
 #include "../server/CVCMIServer.h"
 
-#ifndef VCMI_MOBILE
-#include <boost/process/child.hpp>
-#include <boost/process/io.hpp>
-#endif
-
 #include <future>
 
 ServerThreadRunner::ServerThreadRunner() = default;
@@ -97,7 +92,7 @@ uint16_t ServerProcessRunner::start(uint16_t port, bool connectToLobby, std::sha
        args.push_back("--lobby");
 
    std::error_code ec;
-   child = std::make_unique<boost::process::child>(serverPath, args, ec, boost::process::std_out > logPath);
+   child = std::make_unique<boost::process::v1::child>(serverPath, args, ec, boost::process::v1::std_out > logPath);
 
    if (ec)
        throw std::runtime_error("Failed to start server! Reason: " + ec.message());
diff --git i/client/ServerRunner.h w/client/ServerRunner.h
index d5ba38b53..ac125e417 100644
--- i/client/ServerRunner.h
+++ w/client/ServerRunner.h
@@ -15,6 +15,11 @@ struct StartInfo;
 
 VCMI_LIB_NAMESPACE_END
 
+#ifndef VCMI_MOBILE
+#include <boost/process/v1/child.hpp>
+#include <boost/process/v1/io.hpp>
+#endif
+
 class CVCMIServer;
 
 class IServerRunner
@@ -45,15 +50,11 @@ class ServerThreadRunner : public IServerRunner, boost::noncopyable
 
 #ifndef VCMI_MOBILE
 
-namespace boost::process {
-class child;
-}
-
 /// Class that runs server instance as a child process
 /// Available only on desktop systems where process management is allowed
 class ServerProcessRunner : public IServerRunner, boost::noncopyable
 {
-   std::unique_ptr<boost::process::child> child;
+   std::unique_ptr<boost::process::v1::child> child;
 
 public:
    uint16_t start(uint16_t port, bool connectToLobby, std::shared_ptr<StartInfo> startingInfo) override;
```

**Comment by kambala-decapitator** [comment]
> I don't know why client/ServerRunner.h declares own boost::process::child instead of including boost/process/child directly

It's called "forward declaration", I strongly suggest that you read about it

**Comment by Crandel** [comment]
> I got it compiling with a patch below. I don't know why `client/ServerRunner.h` declares own `boost::process::child` instead of including `boost/process/child` directly, I done just that and it works.

Still the same error after your patch. Are you sure you are using boost 1.86?

**Comment by fenuks** [comment]
Thank you, but why forward declaration is used in this particular case? It's about compile times, or something else? When I tried to update without moving boost include to header, gcc complained:

```
error: inline namespace must be specified at initial definition
   17 | BOOST_PROCESS_V1_INLINE namespace v1
```

It can be fixed moving boost includes in `ServerRunner.cpp` before `#include "ServerRunner.h"`, though.

**Comment by fenuks** [comment]
> Still the same error after your patch. Are you sure you are using boost 1.86?

Yes, I use Arch just like you, and I maintain vcmi-git AUR package. You can apply [package patch from this comment](https://aur.archlinux.org/packages/vcmi-git#comment-989368) to build a new package version. I didn't update PKGBUILD directly, as probably this compilation issue will be fixed quickly.

**Comment by fenuks** [comment]
This version still uses forward declaration and compiles for me:

```diff
diff --git i/client/ServerRunner.cpp w/client/ServerRunner.cpp
index 2a7a0791e..5d518b028 100644
--- i/client/ServerRunner.cpp
+++ w/client/ServerRunner.cpp
@@ -9,17 +9,17 @@
  */
 #include "StdInc.h"
 
+#ifndef VCMI_MOBILE
+#include <boost/process/v1/child.hpp>
+#include <boost/process/v1/io.hpp>
+#endif
+
 #include "ServerRunner.h"
 
 #include "../lib/VCMIDirs.h"
 #include "../lib/CThreadHelper.h"
 #include "../server/CVCMIServer.h"
 
-#ifndef VCMI_MOBILE
-#include <boost/process/child.hpp>
-#include <boost/process/io.hpp>
-#endif
-
 #include <future>
 
 ServerThreadRunner::ServerThreadRunner() = default;
@@ -97,7 +97,7 @@ uint16_t ServerProcessRunner::start(uint16_t port, bool connectToLobby, std::sha
 		args.push_back("--lobby");
 
 	std::error_code ec;
-	child = std::make_unique<boost::process::child>(serverPath, args, ec, boost::process::std_out > logPath);
+	child = std::make_unique<boost::process::v1::child>(serverPath, args, ec, boost::process::v1::std_out > logPath);
 
 	if (ec)
 		throw std::runtime_error("Failed to start server! Reason: " + ec.message());
diff --git i/client/ServerRunner.h w/client/ServerRunner.h
index d5ba38b53..ee932838d 100644
--- i/client/ServerRunner.h
+++ w/client/ServerRunner.h
@@ -45,15 +45,16 @@ class ServerThreadRunner : public IServerRunner, boost::noncopyable
 
 #ifndef VCMI_MOBILE
 
-namespace boost::process {
+namespace boost::process::v1 {
 class child;
 }
 
+
 /// Class that runs server instance as a child process
 /// Available only on desktop systems where process management is allowed
 class ServerProcessRunner : public IServerRunner, boost::noncopyable
 {
-	std::unique_ptr<boost::process::child> child;
+	std::unique_ptr<boost::process::v1::child> child;
 
 public:
 	uint16_t start(uint16_t port, bool connectToLobby, std::shared_ptr<StartInfo> startingInfo) override;
```

**Comment by Crandel** [comment]
Thank you @fenuks now it is working for me. I will attach also my patch, which is a little different than yours, as I'm installing [vcmi](https://aur.archlinux.org/packages/vcmi) 1.5.7 version from release page

```diff
diff --git a/client/ServerRunner.cpp b/client/ServerRunner.cpp
index 8ab4df8..36765de 100644
--- a/client/ServerRunner.cpp
+++ b/client/ServerRunner.cpp
@@ -9,16 +9,17 @@
  */
 #include "StdInc.h"
 
+#ifndef VCMI_MOBILE
+#include <boost/process/v1/child.hpp>
+#include <boost/process/v1/io.hpp>
+#endif
+
 #include "ServerRunner.h"
 
 #include "../lib/VCMIDirs.h"
 #include "../lib/CThreadHelper.h"
 #include "../server/CVCMIServer.h"
 
-#ifndef VCMI_MOBILE
-#include <boost/process/child.hpp>
-#include <boost/process/io.hpp>
-#endif
 
 ServerThreadRunner::ServerThreadRunner() = default;
 ServerThreadRunner::~ServerThreadRunner() = default;
@@ -84,7 +85,7 @@ void ServerProcessRunner::start(uint16_t port, bool connectToLobby, std::shared_
 		args.push_back("--lobby");
 
 	std::error_code ec;
-	child = std::make_unique<boost::process::child>(serverPath, args, ec, boost::process::std_out > logPath);
+	child = std::make_unique<boost::process::v1::child>(serverPath, args, ec, boost::process::v1::std_out > logPath);
 
 	if (ec)
 		throw std::runtime_error("Failed to start server! Reason: " + ec.message());
diff --git a/client/ServerRunner.h b/client/ServerRunner.h
index d045e0c..a89bc87 100644
--- a/client/ServerRunner.h
+++ b/client/ServerRunner.h
@@ -45,7 +45,7 @@ public:
 
 #ifndef VCMI_MOBILE
 
-namespace boost::process {
+namespace boost::process::v1 {
 class child;
 }
 
@@ -53,7 +53,7 @@ class child;
 /// Available only on desktop systems where process management is allowed
 class ServerProcessRunner : public IServerRunner, boost::noncopyable
 {
-	std::unique_ptr<boost::process::child> child;
+	std::unique_ptr<boost::process::v1::child> child;
 
 public:
 	void start(uint16_t port, bool connectToLobby, std::shared_ptr<StartInfo> startingInfo) override;
```

**Comment by kambala-decapitator** [comment]
> why forward declaration is used in this particular case? It's about compile times, or something else?

I think it's always about compile time

**Comment by fenuks** [comment]
> Thanks for investigation, will make patch that would work with both old & new boost.

Thank you for including them.

> For 1.5.X builds you might want to apply these patches on your side (e.g. in AUR) - new 1.5.X release is unlikely.
Will fix for develop / 1.6.

I only maintain vcmi-git on AUR, as long develop compiles, I'm happy.

> I think it's always about compile time

I thought about it a bit, and perhaps sometimes it would be beneficial if distributed headers are free from direct dependency on other library headers? Could make it easier to change implementation?

**Comment by IvanSavenko** [comment]
> I thought about it a bit, and perhaps sometimes it would be beneficial if distributed headers are free from direct dependency on other library headers? Could make it easier to change implementation?

Such breaking changes are fairly rare. From what I see, the previous case where boost had breaking change for vcmi was in boost 1.72 - over 4 years ago.
Other libraries are even more stable. FFmpeg sometimes deprecates stuff too, but usually they provide some compatibility support.

So I'd rather stick to using forward declarations. For somebody familiar with c++ issues like this one are easy to solve, main problem this time was that I don't have newest boost so can't test it on my system.
