### ISSUE TITLE
Should a CI matrix entry be a added that uses gcc-13?

### ISSUE THREAD

**Issue by Kuxe** [vcmi/vcmi#3407]
> Should a CI matrix entry be a added that uses gcc-13?
>
> Available gcc versions:
https://github.com/actions/runner-images/pull/8562/files
Selecting the version to be used:
https://github.com/actions/runner-images/issues/2503

_Originally posted by @Alexander-Wilms in https://github.com/vcmi/vcmi/issues/3399#issuecomment-1872372094_

This question came up when fixing compilation errors I encountered locally on Arch Linux, where `gcc 13.2.1` is what you get. I've verified locally already that building with https://github.com/vcmi/vcmi/pull/3399 on `gcc 13.2.1` via:
```
cmake --preset linux-gcc-release && cmake --build --preset linux-gcc-release
```
works. So adding a CI entry *should* just be a matter of adding a job that builds with `gcc 13.2.1` in addition to `gcc 9.4.0` ([which is currently used](https://github.com/vcmi/vcmi/actions/runs/7360151376/job/20036022291#step:12:26)).

**Comment by IvanSavenko** [comment]
> Should a CI matrix entry be a added that uses gcc-13? 

Don't see need for *new* entries. We already use CI rather heavily, resulting in queue when activity in vcmi repo is high.
However might not be a bad idea to configure gcc versions and use oldest available gcc (for example) for debug build and newest one - for release build.
