### ISSUE TITLE
sdl2_ttf 2.24.0 cause VCMI 1.6.2 compilation error

### ISSUE THREAD

**Issue by AngryPenguinPL** [vcmi/vcmi#5207]
**Describe the bug**
After upgrading sdl2_ttf from version 2.22.0 to 2.24.0, the VCMI 1.6.2 package does not compile correctly with Clang. I see this error.

After downgrading sdl2_ttf to 2.22.0, the compilation works fine.

```
In file included from /builddir/build/BUILD/vcmi-1.6.2-build/vcmi-1.6.2/client/renderSDL/CTrueTypeFont.cpp:23:
DEBUG util.py:461:  /usr/include/SDL2/SDL_ttf.h:165:16: [0;1;31merror: type alias 'TTF_Font' cannot be referenced with the 'struct' specifier
DEBUG util.py:461:    165 | typedef struct TTF_Font TTF_Font;
DEBUG util.py:461:        | [0;1;32m               ^
DEBUG util.py:461:  /builddir/build/BUILD/vcmi-1.6.2-build/vcmi-1.6.2/client/renderSDL/CTrueTypeFont.h:20:7: [0;1;36mnote: declared here
DEBUG util.py:461:     20 | using TTF_Font = struct _TTF_Font;
DEBUG util.py:461:        | [0;1;32m      ^
DEBUG util.py:461:  1 error generated.
```

Full build log: http://file-store.openmandriva.org/api/v1/file_stores/7f69c23336b609c0c4e308461ce899b62efa34d5.log?show=true

**To Reproduce**

1. Install sdl2_ttf 2.24.0 devel
2. Try compile VCMI 1.6.2 with it
3. See error

- OS: [e.g. Windows, macOS Intel, macOS ARM, Android, Linux, iOS] Linux
- Version: [VCMI version] 1.6.2

**Comment by IvanSavenko** [comment]
Can you check whether this change would help?
```diff
diff --git a/client/renderSDL/CTrueTypeFont.h b/client/renderSDL/CTrueTypeFont.h
index 87a9ac484..da9e933ec 100644
--- a/client/renderSDL/CTrueTypeFont.h
+++ b/client/renderSDL/CTrueTypeFont.h
@@ -17,7 +17,7 @@ VCMI_LIB_NAMESPACE_END

 class CBitmapFont;

-using TTF_Font = struct _TTF_Font;
+typedef struct _TTF_Font TTF_Font;

 class CTrueTypeFont final : public IFont
 {
```

**Comment by IvanSavenko** [comment]
Ah, missed that `_`.
Yeah, needs version check

**Comment by AngryPenguinPL** [comment]
hmm added @kambala-decapitator if and build failed with:

```
 In file included from /builddir/build/BUILD/vcmi-1.6.2-build/vcmi-1.6.2/client/renderSDL/FontChain.cpp:13:
DEBUG util.py:461:  /builddir/build/BUILD/vcmi-1.6.2-build/vcmi-1.6.2/client/renderSDL/CTrueTypeFont.h:19:24: [0;1;31merror: floating point literal in preprocessor expression
DEBUG util.py:461:     19 | #if SDL_TTF_VERSION <= 2.22
DEBUG util.py:461:        | [0;1;32m                       ^
DEBUG util.py:461:  /builddir/build/BUILD/vcmi-1.6.2-build/vcmi-1.6.2/client/renderSDL/CTrueTypeFont.h:26:24: [0;1;31merror: use of undeclared identifier 'TTF_Font'
DEBUG util.py:461:     26 |         const std::unique_ptr<TTF_Font, void (*)(TTF_Font*)> font;
DEBUG util.py:461:        | [0;1;32m                              ^
DEBUG util.py:461:  /builddir/build/BUILD/vcmi-1.6.2-build/vcmi-1.6.2/client/renderSDL/CTrueTypeFont.h:32:2: [0;1;31merror: unknown type name 'TTF_Font'
DEBUG util.py:461:     32 |         TTF_Font * loadFont(const JsonNode & config);
DEBUG util.py:461:        | [0;1;32m        ^
DEBUG util.py:461:  /builddir/build/BUILD/vcmi-1.6.2-build/vcmi-1.6.2/client/renderSDL/FontChain.cpp:79:8: [0;1;31merror: no matching member function for call to 'insert'
DEBUG util.py:461:     79 |         chain.insert(chain.begin(), std::make_unique<CTrueTypeFont>(trueTypeConfig));
DEBUG util.py:461:        | [0;1;32m        ~~~~~~^~~~~~
DEBUG util.py:461:  /usr/bin/../lib64/gcc/x86_64-openmandriva-linux-gnu/14.2.0/../../../../include/c++/14.2.0/bits/stl_vector.h:1364:7: [0;1;36mnote: candidate function not viable: no known conversion from 'unique_ptr<[0;1;36mCTrueTypeFont, default_delete<[0;1;36mCTrueTypeFont>>' to '[0;1;36mconst unique_ptr<[0;1;36mIFont, default_delete<[0;1;36mIFont>>' for 2nd argument
DEBUG util.py:461:   1364 |       insert(const_iterator __position, const value_type& __x);
DEBUG util.py:461:        | [0;1;32m      ^                                 ~~~~~~~~~~~~~~~~~~~~~
DEBUG util.py:461:  /usr/bin/../lib64/gcc/x86_64-openmandriva-linux-gnu/14.2.0/../../../../include/c++/14.2.0/bits/stl_vector.h:1395:7: [0;1;36mnote: candidate function not viable: no known conversion from 'unique_ptr<[0;1;36mCTrueTypeFont, default_delete<[0;1;36mCTrueTypeFont>>' to 'unique_ptr<[0;1;36mIFont, default_delete<[0;1;36mIFont>>' for 2nd argument
DEBUG util.py:461:   1395 |       insert(const_iterator __position, value_type&& __x)
DEBUG util.py:461:        | [0;1;32m      ^                                 ~~~~~~~~~~~~~~~~
DEBUG util.py:461:  /usr/bin/../lib64/gcc/x86_64-openmandriva-linux-gnu/14.2.0/../../../../include/c++/14.2.0/bits/stl_vector.h:1413:7: [0;1;36mnote: candidate function not viable: no known conversion from '__detail::__unique_ptr_t<CTrueTypeFont>' (aka 'unique_ptr<CTrueTypeFont>') to 'initializer_list<value_type>' (aka 'initializer_list<std::unique_ptr<IFont, std::default_delete<IFont>>>') for 2nd argument
DEBUG util.py:461:   1413 |       insert(const_iterator __position, initializer_list<value_type> __l)
DEBUG util.py:461:        | [0;1;32m      ^                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DEBUG util.py:461:  /usr/bin/../lib64/gcc/x86_64-openmandriva-linux-gnu/14.2.0/../../../../include/c++/14.2.0/bits/stl_vector.h:1439:7: [0;1;36mnote: candidate function not viable: requires 3 arguments, but 2 were provided
DEBUG util.py:461:   1439 |       insert(const_iterator __position, size_type __n, const value_type& __x)
DEBUG util.py:461:        | [0;1;32m      ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DEBUG util.py:461:  /usr/bin/../lib64/gcc/x86_64-openmandriva-linux-gnu/14.2.0/../../../../include/c++/14.2.0/bits/stl_vector.h:1484:2: [0;1;36mnote: candidate function template not viable: requires 3 arguments, but 2 were provided
DEBUG util.py:461:   1484 |         insert(const_iterator __position, _InputIterator __first,
DEBUG util.py:461:        | [0;1;32m        ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DEBUG util.py:461:   1485 |                _InputIterator __last)
DEBUG util.py:461:        | [0;1;32m               ~~~~~~~~~~~~~~~~~~~~~
DEBUG util.py:461:  4 errors generated.
```

**Comment by kambala-decapitator** [comment]
@AngryPenguinPL "something like" :) It was kinda pseudocode, for proper version check check SDL_ttf.h header for macros major / minor versions. And it would be "major == 2 && minor <= 24"

**Comment by Crandel** [comment]
> ```diff
> -using TTF_Font = struct _TTF_Font;
> +typedef struct _TTF_Font TTF_Font;
> ```

```
In file included from /data/linux/bb/vcmi/src/vcmi-1.6.2/client/renderSDL/CTrueTypeFont.cpp:23:
/usr/include/SDL2/SDL_ttf.h:165:16: error: using typedef-name ‘TTF_Font’ after ‘struct’
  165 | typedef struct TTF_Font TTF_Font;
      |                ^~~~~~~~
[ 89%] Building CXX object client/CMakeFiles/vcmiclientcommon.dir/globalLobby/GlobalLobbyLoginWindow.cpp.o
In file included from /data/linux/bb/vcmi/src/vcmi-1.6.2/client/renderSDL/CTrueTypeFont.cpp:11:
/data/linux/bb/vcmi/src/vcmi-1.6.2/client/renderSDL/CTrueTypeFont.h:20:26: note: ‘TTF_Font’ has a previous declaration here
   20 | typedef struct _TTF_Font TTF_Font;
      |                          ^~~~~~~~
/usr/include/SDL2/SDL_ttf.h:165:25: error: conflicting declaration ‘typedef int TTF_Font’
  165 | typedef struct TTF_Font TTF_Font;
      |                         ^~~~~~~~
/data/linux/bb/vcmi/src/vcmi-1.6.2/client/renderSDL/CTrueTypeFont.h:20:26: note: previous declaration as ‘typedef struct _TTF_Font TTF_Font’
   20 | typedef struct _TTF_Font TTF_Font;
```

**Comment by kambala-decapitator** [comment]
@Crandel please read the above comments

**Comment by Crandel** [comment]
> please read the above comments

Yes, I've read it. It is not working without `using TTF_Font = struct _TTF_Font;` too.

```
/data/linux/bb/vcmi/src/vcmi-1.6.2/client/renderSDL/CTrueTypeFont.cpp:42:12: error: no declaration matches ‘TTF_Font* CTrueTypeFont::loadFont(const JsonNode&)’
   42 | TTF_Font * CTrueTypeFont::loadFont(const JsonNode &config)
      |            ^~~~~~~~~~~~~
/data/linux/bb/vcmi/src/vcmi-1.6.2/client/renderSDL/CTrueTypeFont.cpp:42:12: note: no functions named ‘TTF_Font* CTrueTypeFont::loadFont(const JsonNode&)’
/data/linux/bb/vcmi/src/vcmi-1.6.2/client/renderSDL/CTrueTypeFont.h:21:7: note: ‘class CTrueTypeFont’ defined here
   21 | class CTrueTypeFont final : public IFont
      |       ^~~~~~~~~~~~~
/data/linux/bb/vcmi/src/vcmi-1.6.2/client/renderSDL/CTrueTypeFont.cpp: In constructor ‘CTrueTypeFont::CTrueTypeFont(const JsonNode&)’:
/data/linux/bb/vcmi/src/vcmi-1.6.2/client/renderSDL/CTrueTypeFont.cpp:66:14: error: ‘loadFont’ was not declared in this scope
   66 |         font(loadFont(fontConfig), TTF_CloseFont),
      |              ^~~~~~~~
/data/linux/bb/vcmi/src/vcmi-1.6.2/client/renderSDL/CTrueTypeFont.cpp:66:9: error: expression list treated as compound expression in mem-initializer [-fpermissive]
   66 |         font(loadFont(fontConfig), TTF_CloseFont),
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/linux/bb/vcmi/src/vcmi-1.6.2/client/renderSDL/CTrueTypeFont.cpp:73:31: error: request for member ‘get’ in ‘((CTrueTypeFont*)this)->CTrueTypeFont::font’, which is of non-class type ‘const int’
   73 |         TTF_SetFontStyle(font.get(), getFontStyle(fontConfig));
      |                               ^~~
/data/linux/bb/vcmi/src/vcmi-1.6.2/client/renderSDL/CTrueTypeFont.cpp:74:33: error: request for member ‘get’ in ‘((CTrueTypeFont*)this)->CTrueTypeFont::font’, which is of non-class type ‘const int’
   74 |         TTF_SetFontHinting(font.get(),TTF_HINTING_MONO);
      |                                 ^~~
/data/linux/bb/vcmi/src/vcmi-1.6.2/client/renderSDL/CTrueTypeFont.cpp:79:62: error: request for member ‘get’ in ‘((CTrueTypeFont*)this)->CTrueTypeFont::font’, which is of non-class type ‘const int’
   79 |                                          TTF_FontHeight(font.get()),
      |                                                              ^~~
/data/linux/bb/vcmi/src/vcmi-1.6.2/client/renderSDL/CTrueTypeFont.cpp:80:62: error: request for member ‘get’ in ‘((CTrueTypeFont*)this)->CTrueTypeFont::font’, which is of non-class type ‘const int’
   80 |                                          TTF_FontAscent(font.get()),
      |                                                              ^~~
/data/linux/bb/vcmi/src/vcmi-1.6.2/client/renderSDL/CTrueTypeFont.cpp:81:63: error: request for member ‘get’ in ‘((CTrueTypeFont*)this)->CTrueTypeFont::font’, which is of non-class type ‘const int’
   81 |                                          TTF_FontDescent(font.get()),
      |                                                               ^~~
/data/linux/bb/vcmi/src/vcmi-1.6.2/client/renderSDL/CTrueTypeFont.cpp:82:64: error: request for member ‘get’ in ‘((CTrueTypeFont*)this)->CTrueTypeFont::font’, which is of non-class type ‘const int’
   82 |                                          TTF_FontLineSkip(font.get())
      |                                                                ^~~
/data/linux/bb/vcmi/src/vcmi-1.6.2/client/renderSDL/CTrueTypeFont.cpp: In member function ‘virtual size_t CTrueTypeFont::getFontAscentScaled() const’:
/data/linux/bb/vcmi/src/vcmi-1.6.2/client/renderSDL/CTrueTypeFont.cpp:90:36: error: request for member ‘get’ in ‘((const CTrueTypeFont*)this)->CTrueTypeFont::font’, which is of non-class type ‘const int’
   90 |         return TTF_FontAscent(font.get());
      |                                    ^~~
/data/linux/bb/vcmi/src/vcmi-1.6.2/client/renderSDL/CTrueTypeFont.cpp: In member function ‘virtual size_t CTrueTypeFont::getLineHeightScaled() const’:
/data/linux/bb/vcmi/src/vcmi-1.6.2/client/renderSDL/CTrueTypeFont.cpp:95:36: error: request for member ‘get’ in ‘((const CTrueTypeFont*)this)->CTrueTypeFont::font’, which is of non-class type ‘const int’
   95 |         return TTF_FontHeight(font.get());
   ```

**Comment by kambala-decapitator** [comment]
Symbol `_TTF_Font` doesn't exist in 2.24, it was renamed to `TTF_Font` (no leading underscore), see the commit I referenced above

**Comment by Crandel** [comment]
> Symbol `_TTF_Font` doesn't exist in 2.24, it was renamed to `TTF_Font` (no leading underscore), see the commit I referenced above

I'm not C++ developer, so I have very bad idea what should be changed in order to compile successfully. Would be good if you can provide me a working patch

**Comment by Crandel** [comment]
> ```diff
> -using TTF_Font = struct _TTF_Font;
> +typedef struct _TTF_Font TTF_Font;
> ```

So I've tried to remove `_` in `using TTF_Font = struct TTF_Font;` line and the build was successful

**Comment by kambala-decapitator** [comment]
> > ```diff
> 
> > -using TTF_Font = struct _TTF_Font;
> 
> > +typedef struct _TTF_Font TTF_Font;
> 
> > ```
> 
> 
> 
> So I've tried to remove `_` in `using TTF_Font = struct TTF_Font;` line and the build was successful 

Yes, that works, but only for v2.24 (I think you can drop the `using` line completely). For compatibility with earlier versions will provide patch / PR later today.

**Comment by kambala-decapitator** [comment]
opened PR, here's the patch: https://[patch-diff.githubusercontent.com/raw/vcmi/vcmi/pull/5222.patch](https://patch-diff.githubusercontent.com/raw/vcmi/vcmi/pull/5222.patch)
