### ISSUE TITLE
Failed to compile with sdl2_mixer 2.8.1

### ISSUE THREAD

**Issue by Crandel** [vcmi/vcmi#5408]
**Describe the bug**
Failed to compile with sdl2_mixer 2.8.1 with error

```
[ 86%] Building CXX object client/CMakeFiles/vcmiclientcommon.dir/render/CDefFile.cpp.o
In file included from /data/linux/bb/vcmi/src/vcmi-1.6.5/client/media/CMusicHandler.cpp:25:
/usr/include/SDL2/SDL_mixer.h:269:16: error: using typedef-name ‘using Mix_Music = struct _Mix_Music’ after ‘struct’
  269 | typedef struct Mix_Music Mix_Music;
      |                ^~~~~~~~~
In file included from /data/linux/bb/vcmi/src/vcmi-1.6.5/client/media/CMusicHandler.cpp:11:
/data/linux/bb/vcmi/src/vcmi-1.6.5/client/media/CMusicHandler.h:18:7: note: ‘using Mix_Music = struct _Mix_Music’ has a previous declaration here
   18 | using Mix_Music = struct _Mix_Music;
      |       ^~~~~~~~~
/usr/include/SDL2/SDL_mixer.h:269:26: error: conflicting declaration ‘typedef int Mix_Music’
  269 | typedef struct Mix_Music Mix_Music;
      |                          ^~~~~~~~~
/data/linux/bb/vcmi/src/vcmi-1.6.5/client/media/CMusicHandler.h:18:7: note: previous declaration as ‘using Mix_Music = struct _Mix_Music’
   18 | using Mix_Music = struct _Mix_Music;
      |       ^~~~~~~~~
[ 86%] Building CXX object client/CMakeFiles/vcmiclientcommon.dir/render/Canvas.cpp.o
[ 87%] Building CXX object client/CMakeFiles/vcmiclientcommon.dir/render/CanvasImage.cpp.o
[ 87%] Building CXX object client/CMakeFiles/vcmiclientcommon.dir/render/ColorFilter.cpp.o
[ 87%] Building CXX object client/CMakeFiles/vcmiclientcommon.dir/render/Colors.cpp.o
make[2]: *** [client/CMakeFiles/vcmiclientcommon.dir/build.make:1248: client/CMakeFiles/vcmiclientcommon.dir/media/CMusicHandler.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1248: client/CMakeFiles/vcmiclientcommon.dir/all] Error 2
```

**To Reproduce**

1. Build with sdl2_mixer 2.8.1

**Expected behavior**
Build is successful

**Actual behavior**
Build failed

**Did it work earlier?**
It worked with sdl_mixer 2.8.0

**Version**

- OS: Arch Linux 
- Version: 1.6.5

**Additional context**

**Comment by kambala-decapitator** [comment]
why do you think it's Boost related if the error clearly points at SDL_mixer? :)

**Comment by Crandel** [comment]
Hmm sdl2_mixer package was updated too. 2.8.0-1 -> 2.8.1-1

**Comment by Crandel** [comment]
The fix is to change [this line](https://github.com/vcmi/vcmi/blob/develop/client/media/CMusicHandler.h#L18) to 

```
typedef struct Mix_Music Mix_Music;
```

**Comment by kambala-decapitator** [comment]
> The fix is to change [this line](https://github.com/vcmi/vcmi/blob/develop/client/media/CMusicHandler.h#L18) to
> 
> ```
> typedef struct Mix_Music Mix_Music;
> ```

starting with v2.8.1 we don't need this typedef in our code at all as it's present in SDL_Mixer'e header. But for earlier versions we still need it, so the fix would be to guard it with version check macro.

Has been renamed in v2.8.1 indeed: https://github.com/libsdl-org/SDL_mixer/commit/063804ab9bb13b95b54b258ccf4005bf5fcd13b0

**Comment by Crandel** [comment]
> starting with v2.8.1 we don't need this typedef in our code at all as it's present in SDL_Mixer's header.

If I just remove it, it is failing with message

```
In file included from /data/linux/bb/vcmi/src/vcmi-1.6.5/client/media/CMusicHandler.cpp:11:
/data/linux/bb/vcmi/src/vcmi-1.6.5/client/media/CMusicHandler.h:24:2: error: unknown type name 'Mix_Music'
   24 |         Mix_Music * music;
```

**Comment by josch** [comment]
Thank you for your patch! We now carry it in Debian: https://sources.debian.org/src/vcmi/1.6.5%2Bdfsg-1/debian/patches/0004-use-Mix_Music-from-SDL_Mixer-directly.patch/

**Comment by nerozero** [comment]
cannot compile on arch

**Comment by kambala-decapitator** [comment]
> cannot compile on arch

Have you applied the patch?

**Comment by nerozero** [comment]
> Have you applied the patch?

compiling with a patch at the moment...

**Comment by nerozero** [comment]
It is compiling with the patch. I was confused because of the pull request where approved but the code isn't seems to be there...

**Comment by kambala-decapitator** [comment]
The pr targeted beta branch (1.6.x releases), and you're probably on develop branch. Beta -> develop merge will be done after 1.6.6 release most probably.

**Comment by nerozero** [comment]
@kambala-decapitator exactly, yes, thanks !
